### PR TITLE
[fwutil]: Add firmware management utility

### PR DESCRIPTION
**Pull request by mudsut4ke**
**- What I did**

- Add firmware management CLI
- Add support for query querying module's firmware version
- Add support for Install firmware image to module

**- New command syntax:**
```
root@sonic:~# fwutil show version
root@sonic:~# fwutil install -m <module name> <path/url>
```
**- Example of command output**
```
root@sonic:~# fwutil show version
Module    Submodule    Version
--------  -----------  ---------
BIOS                   5.6.5
CPLD      CPLD4        4.4
CPLD      CPLD5        5.4
CPLD      CPLD2        2.5
CPLD      CPLD3        3.4
CPLD      CPLD1        1.4

root@sonic:~# fwutil install -m CPLD http://192.168.20.106/slx/Seastone_CPLD_V0_7.vme
Downloading image...
Command: ispvm /tmp/fw_image.vme

                 Lattice Semiconductor Corp.

             ispVME(tm) V12.2 Copyright 1998-2011.

For daisy chain programming of all in-system programmable devices

Processing virtual machine file (/tmp/fw_image.vme)......

CREATED BY: ispVM(R) System Version 18.0.1
CREATION DATE: 12/06/18 16:03:31  

+=======+
| PASS! |
+=======+

Done

```

### CODE REVIEW

**Comment by BeckHe** [comment]
Please add Bo Lv as mandatory reviewer for SONiC related, I can be the optional, not the block of the merge actions.

**Comment by BeckHe** [comment]
I believer it comes from a customer project, please discuss with Bo Lv about the possibility to commit source to community. Currently seems it is a platform specific/dependent tool, not a platform independent tool.

**Review by larryming — COMMENTED** [review]
Can you send code flow to us so we can understand your design?

**Comment by mudsut4ke** [comment]
@larryming 

The main.py code just call platform specific fwutil class to take action
For HLX/SLX the fwutil code is here: https://github.com/SW-CSV/sonic-buildimage/pull/2

**Comment by mudsut4ke** [comment]
@larryming 

https://github.com/SW-CSV/sonic-buildimage/pull/2
The platform specific was approved
What about here ?

**Pull request closed without merging**
